### ISSUE TITLE
[Enhancement] Cancel dyeing if wool colored in the same dye color.

### ISSUE THREAD

**Issue by Ghostlyr** [QVBA/RightClickDye#2]
Thank you for  helpful mod. I think, it would be essential checking so I have often click once more and the dye goes nowhere. I very much hope you implement this small improvement.

**Comment by QVBA** [comment]
Just got back to mod development, will do so now :).
Thanks for your interest in the mod.

**Comment by QVBA** [comment]
Fixed.

**Comment by Ghostlyr** [comment]
Thanks!
