### ISSUE TITLE
[Enhancement] Ability to dyeing the carpets, hardened clay and glass + configuration to disable/enable functions.

### ISSUE THREAD

**Issue by Ghostlyr** [QVBA/RightClickDye#3]
It would be great if be dyable not only wool, but also dyeing the carpets, hardened clay and glass. Perhaps someone would think any possibility too much dishonesty nice to be able to turn off any function.

**Comment by QVBA** [comment]
The ability to dye carpets/glass has been added in commit 9 and an update is being pushed to minecraft.curseforge now.. Unfortunately I was not able to find a way to do the same with hardened clay but I will work on that at some point today.
