### ISSUE TITLE
New idea - paint pots

### ISSUE THREAD

**Issue by Ghostlyr** [QVBA/RightClickDye#4]
I have an idea for a new or improvements to of this - new crafttable buckets of paint. Or possible to make a mechanism that mixed the dye and water.  This would make the compatibility with the dyes of the modifications easier and would give more opportunities.
They might be added "spilling" effects with particles, smooth change of block color or other effects.
The thing is simple, but opportunities to do it more interesting are huge.  It would be cool.

**Comment by QVBA** [comment]
This mod was created with the intention to simply add vanilla minecraft functionality. I would like people playing a modpack with this mod installed to not even know it exists and just believe that it's a vanilla function. As such I won't be accepting this suggestion, but am considering making another mod in the future which will definitely have this added.
